version: '3.9'

services:
  crdb:
    image: cockroachdb/cockroach:v23.1.10
    container_name: crdb
    ports:
      - '26257:26257'
      - '8080:8080'
    command: start-single-node --insecure
    volumes:
      - 'crdb-data:/cockroach/cockroach-data'
    networks:
      - my_network

  crdbTest:
    image: cockroachdb/cockroach:v23.1.10
    container_name: crdbTest
    ports:
      - '26258:26257'
      - '8081:8080'
    command: start-single-node --insecure
    volumes:
      - 'crdb-data-test:/cockroach/cockroach-data-test'
    networks:
      - my_network

volumes:
  crdb-data:
  crdb-data-test:

networks:
  my_network:
    driver: bridge


# Use postgres
# potentially helpful scripts
# "pgadmin": "cmd.exe /C start http://127.0.0.1:5050",
# "pgadmin:win": "start http://127.0.0.1:5050",

#version: '3.9'
#
#services:
#  db:
#    image: 'postgres:15'
#    environment:
#      POSTGRES_PASSWORD: asdfasdf
#      POSTGRES_USER: postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - 'db-data:/var/lib/postgresql/data'
#    networks:
#      - my_network
#    command: -p 5432
#
#  dbTest:
#    image: 'postgres:15'
#    environment:
#      POSTGRES_PASSWORD: asdfasdf
#      POSTGRES_USER: postgres
#    ports:
#      - '5433:5433'
#    volumes:
#      - 'db-data-test:/var/lib/postgresql/data'
#    networks:
#      - my_network
#    command: -p 5433
#
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - '5050:80'
#    volumes:
#      - 'pgadmin-data:/var/lib/pgadmin'
#    networks:
#      - my_network
#
#volumes:
#  db-data:
#  db-data-test:
#  pgadmin-data:
#
#networks:
#  my_network:
#    driver: bridge
#