version: '3.9'

services:
  db:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    networks:
      - my_network
    command: -p 5432

  dbTest:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: postgres
    ports:
      - '5433:5433'
    volumes:
      - 'db-data-test:/var/lib/postgresql/data'
    networks:
      - my_network
    command: -p 5433

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    networks:
      - my_network

volumes:
  db-data:
  db-data-test:
  pgadmin-data:

networks:
  my_network:
    driver: bridge
