version: "3.9"

services:

  crdb:
    image: cockroachdb/cockroach:v23.1.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./cockroach-data/crdb:/cockroach/cockroach-data"
  crdbTest:
    image: cockroachdb/cockroach:v23.1.2
    ports:
      - "26258:26257"
      - "8081:8088"
    command: start-single-node --insecure
    volumes:
      - "./cockroach-data/crdb:/cockroach/cockroach-data-test"
