import "@/styles/index.css";

// import "@/styles/globals.css";
import { ApolloWrapper } from "@/lib/apollo-wrapper";

// import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"gradient leading-normal tracking-normal text-white"}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
