name: Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Run tests
      - name: Run Tests
        run: bun run test
